#import "/prelude.typ": *

== Structuring Our Study

As I have argued in greater length #link("https://cs.brown.edu/~sk/Publications/Papers/Published/sk-teach-pl-post-linnaean/")[elsewhere], it is more meaningful to think of programming languages as aggregates of _features_. The features are the building blocks. Of course, once combined, languages are more like compounds than like mixtures: the features interact in ways that may not be easy to predict. Understanding both the features and their compositions is then a valuable way to approach a language.

The book revolves around a central idea, _SMoL_, the Standard Model of Languages. This is the embodiment of the computational core of many of our widely-used programming languages, from C\# and Java to JavaScript, Lua, Python, and Ruby to OCaml and Racket. The astute reader will notice that this commonality pays no respect to "paradigms". Rather, all these languages (and many others), to a large extent, have a common computational core: safe runtime systems, automated memory management, eager evaluation, first-class lexically-scoped functions, first-order mutable variables, and first-class mutable structures. Contemporary programming demands a deep understanding of these. For instance, I believe you cannot make sense of concurrency with mutation, static members, or ownership, without understanding SMoL.

However, because languages are artificial and programming is an almost infinitely malleable material, even "standard" features have historically seen variation. Therefore, while we progress _across_ features, we also want to study variation _within_ them. We do this by using the #link("https://cs.brown.edu/~sk/Publications/Papers/Published/pkf-teach-pl-exp-adv-think/")[mystery language] approach: with a fixed syntax, we explore the different ways the same feature can behave. This hopes to build on the cognitive theory of #link("https://www.cultofpedagogy.com/contrasting-cases/")[contrasting cases] to improve learning.

What goes in SMoL is, of course, a judgment call: when a feature isn't present across a large number of diverse languages (like static types), or shows too much variation between languages (like objects), I argue that it's no longer part of the _standard_ model. But it is not a _value_ judgment: in this book we explore SMoL in some depth,  then turn our attention to several non-"standard" features that are not only important but also beautiful and fascinating.

Turning to implementation, the book provides another pillar: _SImPl_, the Standard Implementation Plan. This is the idea that programming languages are usefully thought of in terms of an abstract syntax tree; this tree is represented well by an algebraic datatype; and a program that processes this tree is a recursive function that is largely guided by the structure of the type. This level of description encompasses both of the standard media for evaluation: interpreters and compilers. It also captures the essence of type-checkers, type inference, static analysis, and more. Thus, students should gain facility with this structure for when they want to implement their own language experiments.
