#import "/prelude.typ": *

== Desugaring

This introduces a distinction between a _core_ language and a _surface_ language. The surface language may have various conveniences, but these get translated into the core language, whose constructs are all handled directly. The extra constructs---those that make it "sweeter" to program---are called _syntactic sugar_. The program that translates surface programs down to the core is called a _desugarer_, because it removes sugar. (In principle, a desugarer is actually a _compiler_ from the surface language to the core language. However, since the core language is a _sub_-language of the surface, this is a very special case of compilation, and we find it useful to have a special term to distinguish it from general compilation. Just like we find it useful to have a special term to distinguish `for` from the general `while`…)

#aside[
  In a real implementation, this compilation requires a little more care. Suppose you make an error using `for`, but the error was reported in terms of `while`: you'd be pretty confused, because you never did type the `while`. As a special case, you may be a student who doesn't even know what `while` _is_! Modern desugaring systems, such as that in Racket, have special support to take care of this in most of the common cases.
]

There are actually many more desugarings in real languages. For instance, `and` and `or` can desugar into nested `if`s. In JavaScript, `o.x` desugars into `o["x"]` (which will be relevant in a while). In many languages, `x += y` is sugar for `x = x + y`. In Python, `+` desugars into the method `__add__`. In fact, Python has a whole bunch of these desugarings; these methods are called "dunder" methods (short for double-underscore), and a whole programming style of "#link("https://twitter.com/gvanrossum/status/1307712322320785409")[protocols]" has evolved around it. Many languages (like Haskell and Python) have list comprehensions, which desugar into function and method calls. And so on. In short, desugaring is everywhere in programming. If you don't notice it, that's part of the point: it feels like you're working with a larger surface syntax than the implementor has to manage.

There are many ways in which desugaring can be implemented. One way is to parse the program normally, then rewrite the AST into a subset of the same AST. But in some languages, especially those with parenthetical syntax, there are two levels of parsing: the coarser parenthetical level and the finer level of ASTs. This means we can perform rewriting on the parenthetical terms, and the internal AST never needs to know about the sugars (i.e., it need cover only the core language). These are typically called _macro_ systems: systems in which program source (slightly abstracted) is rewritten into program source, before parsing takes place. It's important to understand that _most_ languages have syntactic sugar, but _very few_ languages have macro systems, which provide program rewriting capabilities directly to the programmer (as opposed to hiding them inside the compiler).
