name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v5
      - uses: cognitive-engineering-lab/depot/actions/install@main
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall rheo@0.3.0 && cargo binstall just@1.51.0      
      - run: cd components/code-description && depot build --release
      - run: just link-components
      - run: rheo compile . --pdf --epub --html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/
      - uses: actions/deploy-pages@v4
